// Generated by the windmill services transformer
var test_run = new function() {
    this.test_actions = [
{"params": {"link": "New"}, "method": "click"},
{"params": {"timeout": "20000"}, "method": "waits.forPageLoad"},
{"params": {"text": "test run", "name": "jobname"}, "method": "type"},
{"params": {"name": "jobspec"}, "method": "click"},
{"params": {"text": "131.159.20.57", "name": "jobspec"}, "method": "type"},
{"params": {"name": "submit"}, "method": "click"},
{"params": {"timeout": "20000"}, "method": "waits.forPageLoad"},
{"params": {"link": "Start this Job", "timeout": "8000"}, "method": "waits.forElement"},
{"params": {"link": "Start this Job"}, "method": "click"},
{"params": {"timeout": "20000"}, "method": "waits.forPageLoad"},
{"params": {"timeout": "8000", "id": "flash"}, "method": "waits.forElement"},
{"params": {"string": "Job started"}, "method": "asserts.assertNode"},
{"params": {"link": "Show Result"}, "method": "click"},
{"params": {"timeout": "20000"}, "method": "waits.forPageLoad"},
{"params": {"timeout": "8000", "id": "main"}, "method": "waits.forElement"},
{"params": {"string": "131.159.20.57, franklin.net.in.tum.de"}, "method": "asserts.assertNode"},
{"params": {"link": "Home", "timeout": "8000"}, "method": "waits.forElement"},
{"params": {"link": "Home"}, "method": "click"},
{"params": {"timeout": "20000"}, "method": "waits.forPageLoad"},
{"params": {"timeout": "8000", "name": "delete"}, "method": "waits.forElement"},
{"params": {"name": "delete"}, "method": "click"},
{"params": {"timeout": "20000"}, "method": "waits.forPageLoad"}
    ];
}
